### ISSUE TITLE
should send an moer specific execption when receiving 'XML-RPC server not enabled.' from the server

### ISSUE THREAD

**Issue by Psycojoker** [kynan/dokuwikixmlrpc#2]
Hello,

This will be way more readable than:

    Traceback (most recent call last):
      File "script.py", line 1, in <module>
        from dokuwikixmlrpc import DokuWikiClient; DokuWikiClient("http://wiki.cerkinfo.be", "Bram", "p0ulet0478")
      File "/home/psycojoker/code/python/dokuwikixmlrpc/dokuwikixmlrpc.py", line 113, in __init__
        self.dokuwiki_version = self._dokuwiki_version()
      File "/home/psycojoker/code/python/dokuwikixmlrpc/dokuwikixmlrpc.py", line 145, in _dokuwiki_version
        return self._xmlrpc.dokuwiki.getVersion()
      File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
        return self.__send(self.__name, args)
      File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
        verbose=self.__verbose
      File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
        return self.single_request(host, handler, request_body, verbose)
      File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
        return self.parse_response(response)
      File "/usr/lib/python2.7/xmlrpclib.py", line 1467, in parse_response
        p.feed(data)
      File "/usr/lib/python2.7/xmlrpclib.py", line 557, in feed
        self._parser.Parse(data, 0)
    xml.parsers.expat.ExpatError: syntax error: line 1, column 0

Which doesn't inform in any manner of the actual error.

**Comment by kynan** [comment]
This is somewhat tricky to handle: Python's xmlRPC lib seems to always expect a valid xml response and DokuWiki is non-compliant. The only workaround I can see is catching an `ExpatError` and assuming it is due to having received a "XML-RPC server not enabled".
